import { useEffect, useState } from 'react';
import { ArrowLeft, BookOpen, ClipboardList, PlayCircle, Users, UserRound } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { AppShell } from '@/components/AppShell';
import api from '@/services/api';

interface Stats { totalChapters?: number; totalCourses?: number; totalStudents?: number; totalLessons?: number; totalExams?: number; activeAccesses?: number; }
export default function Dashboard() {
  const navigate = useNavigate(); const [stats, setStats] = useState<Stats>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { api.get('/admin/stats').then((response) => setStats(response.data.data)).catch(() => setError('تعذر تحميل الإحصاءات.')).finally(() => setLoading(false)); }, []);
  const cards = [{ label: 'أبواب المنهج', value: stats.totalChapters ?? stats.totalCourses ?? 0, icon: BookOpen, tone: 'teal' }, { label: 'الدروس المضافة', value: stats.totalLessons ?? 0, icon: PlayCircle, tone: 'sand' }, { label: 'الطلاب', value: stats.totalStudents ?? 0, icon: Users, tone: 'mint' }, { label: 'الامتحانات', value: stats.totalExams ?? 0, icon: ClipboardList, tone: 'lilac' }];
  return <AppShell><div className="admin-page-stack"><section className="admin-welcome"><div><span className="admin-eyebrow">مساحة المدرس</span><h1>صباح الخير، Mr Electron</h1><p>من هنا تتابع المنهج، تفتح الأبواب للطلاب، وتضيف امتحاناتك.</p></div><div className="admin-welcome-actions"><button type="button" className="admin-primary" onClick={() => navigate('/students')}><Users size={16} /> تفعيل طالب</button><button type="button" className="admin-secondary" onClick={() => navigate('/curriculum')}>إدارة المنهج <ArrowLeft size={15} /></button></div></section>{error && <div className="admin-error" role="alert">{error}</div>}{loading ? <div className="admin-loading-panel"><span className="spinner" /> جارٍ تحميل الأرقام...</div> : <div className="admin-metric-grid">{cards.map(({ label, value, icon: Icon, tone }) => <article className="admin-metric" key={label}><span className={`admin-metric-icon ${tone}`}><Icon size={19} /></span><strong>{value}</strong><span>{label}</span></article>)}</div>}<div className="admin-dashboard-grid"><section className="admin-action-card"><div className="admin-section-heading"><div><span className="admin-eyebrow">مسارات سريعة</span><h2>ابدأ من هنا</h2></div></div><button type="button" onClick={() => navigate('/curriculum')}><span className="quick-icon"><BookOpen size={17} /></span><span><strong>رتّب الأبواب والدروس</strong><small>أضف بابًا واختر الترم والصف</small></span><ArrowLeft size={16} /></button><button type="button" onClick={() => navigate('/students')}><span className="quick-icon mint"><UserRound size={17} /></span><span><strong>فعّل وصول الطلاب</strong><small>الباب يفتح كل دروسه تلقائيًا</small></span><ArrowLeft size={16} /></button><button type="button" onClick={() => navigate('/exams/manage')}><span className="quick-icon lilac"><ClipboardList size={17} /></span><span><strong>أنشئ امتحانًا</strong><small>عام أو مرتبط بباب</small></span><ArrowLeft size={16} /></button></section><section className="admin-note-card"><span className="admin-orbit" aria-hidden="true"><i /><i /><i /></span><span className="admin-eyebrow">قاعدة الوصول</span><h2>فعّل الباب مرة،<br />وافتح دروسه كلها.</h2><p>لو فيه درس محتاج يفضل مقفول، تقدر تعدّل استثناءه من شاشة الطالب.</p><button type="button" className="admin-text-link" onClick={() => navigate('/students')}>افتح مصفوفة الوصول <ArrowLeft size={15} /></button></section></div></div></AppShell>;
}
