import { useEffect, useState } from 'react';
import { ArrowRight, CheckCircle2, FileText, UserRound } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { AppShell } from '@/components/AppShell';
import { Exam, getExamById, getExamSubmissions, Submission } from '@/services/examsService';

export default function ExamResultsPage() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const [exam, setExam] = useState<Exam | null>(null); const [submissions, setSubmissions] = useState<Submission[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { if (!id) return; Promise.all([getExamById(id), getExamSubmissions(id)]).then(([examData, submissionData]) => { setExam(examData); setSubmissions(submissionData); }).catch(() => setError('تعذر تحميل النتائج.')).finally(() => setLoading(false)); }, [id]);
  if (loading) return <AppShell><div className="admin-loading-panel"><span className="spinner" /> جارٍ تحميل النتائج...</div></AppShell>;
  return <AppShell><div className="admin-page-stack"><button type="button" className="admin-back-link" onClick={() => navigate(`/admin/exams/${id}`)}><ArrowRight size={17} /> العودة للامتحان</button><section className="admin-page-intro"><div><span className="admin-eyebrow">متابعة الطلاب</span><h1>نتائج {exam?.title || 'الامتحان'}</h1><p>راجع محاولات الطلاب ودرجاتهم.</p></div><span className="access-summary"><strong>{submissions.length}</strong> محاولات</span></section>{error && <div className="admin-error">{error}</div>}{submissions.length === 0 ? <div className="admin-empty"><CheckCircle2 size={26} /><h2>لا توجد محاولات بعد</h2><p>ستظهر النتائج هنا بعد حل الطلاب للامتحان.</p></div> : <section className="admin-panel"><div className="admin-results-table"><div className="admin-table-head"><span>الطالب</span><span>الدرجة</span><span>النسبة</span><span>التاريخ</span></div>{submissions.map((submission) => { const student = typeof submission.userId === 'object' ? submission.userId : null; const percentage = submission.totalMarks ? Math.round((submission.score / submission.totalMarks) * 100) : 0; return <article className="admin-result-row" key={submission._id}><span className="admin-course-title"><span className="student-avatar"><UserRound size={14} /></span><span><strong>{student?.name || 'طالب'}</strong><small>{student?.phone || '—'}</small></span></span><strong>{submission.score} / {submission.totalMarks}</strong><span className={percentage >= 50 ? 'admin-status open' : 'admin-status closed'}>{percentage}٪</span><span className="admin-muted">{new Date(submission.submittedAt).toLocaleDateString('ar-EG')}</span></article>; })}</div></section>}</div></AppShell>;
}
