import { FormEvent, useState } from 'react';
import type { AxiosError } from 'axios';
import { ArrowLeft, Eye, EyeOff, Settings2 } from 'lucide-react';
import { useNavigate } from '@/lib/router';
import { login, setAuthToken, setAuthUser } from '@/services/authService';
import { useAuth } from '@/contexts/AuthContext';

const landingUrl = (import.meta.env.VITE_LANDING_URL || 'http://localhost:5173').replace(/\/+$/, '');

export default function Login() {
  const navigate = useNavigate(); const { login: setUser } = useAuth(); const [phone, setPhone] = useState(''); const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!phone || !password) { setError('اكتب رقم الهاتف وكلمة المرور.'); return; } setLoading(true); setError(''); try { const response = await login({ phone, password }); if (!['admin', 'teacher', 'assistant'].includes(response.data.user.role)) { setError('هذا الحساب لا يملك صلاحية الإدارة.'); return; } setAuthToken(response.token); setAuthUser(response.data.user); setUser(response.data.user); navigate('/dashboard', { replace: true }); } catch (requestError) { const error = requestError as AxiosError<{ message?: string }>; setError(error.response?.data?.message || 'بيانات الدخول غير صحيحة.'); } finally { setLoading(false); } };
  return <div className="admin-auth-page"><div className="admin-auth-decoration" aria-hidden="true"><span /><span /></div><div className="admin-auth-brand"><span className="admin-brand-mark"><span /><span /><span /></span><span><b>mr electron</b><small>مساحة المدرس والإدارة</small></span></div><main className="admin-auth-card"><span className="admin-auth-icon"><Settings2 size={21} /></span><span className="admin-eyebrow">دخول آمن</span><h1>لوحة التحكم</h1><p>أدر المنهج، الدروس، الامتحانات، ووصول طلابك من مكان واحد.</p><form className="admin-form" onSubmit={submit}><label>رقم الهاتف<input value={phone} onChange={(event) => setPhone(event.target.value)} type="tel" inputMode="numeric" placeholder="01xxxxxxxxx" autoComplete="tel" /></label><label>كلمة المرور<span className="admin-input-action"><input value={password} onChange={(event) => setPassword(event.target.value)} type={show ? 'text' : 'password'} placeholder="••••••••" autoComplete="current-password" /><button type="button" onClick={() => setShow((value) => !value)} aria-label="إظهار كلمة المرور">{show ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label>{error && <div className="admin-error" role="alert">{error}</div>}<button type="submit" className="admin-primary full-admin-button" disabled={loading}>{loading ? <><span className="spinner spinner-light" /> جارٍ الدخول...</> : <>الدخول إلى الإدارة <ArrowLeft size={16} /></>}</button></form><p className="admin-auth-foot">هذه المساحة مخصصة لفريق Mr Electron</p><a className="admin-auth-back" href={landingUrl}>الصفحة التعريفية</a></main></div>;
}
