import { useState } from 'react';
import { LockKeyhole, Save, UserRound } from 'lucide-react';
import { AppShell } from '@/components/AppShell';
import { useAuth } from '@/contexts/AuthContext';
import api from '@/services/api';

export default function SettingsPage() {
  const { user, login } = useAuth(); const [name, setName] = useState(user?.name || ''); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const saveProfile = async () => { if (!name.trim()) { setError('اكتب الاسم.'); return; } setSaving(true); setError(''); try { const response = await api.put('/users/profile', { name: name.trim() }); login(response.data.data.user); setMessage('تم حفظ البيانات.'); } catch (requestError: any) { setError(requestError.response?.data?.message || 'تعذر حفظ البيانات.'); } finally { setSaving(false); } };
  const savePassword = async () => { if (!currentPassword || newPassword.length < 6 || newPassword !== confirm) { setError('راجع كلمات المرور وتأكد من التطابق.'); return; } setSaving(true); setError(''); try { await api.put('/users/change-password', { currentPassword, newPassword }); setCurrentPassword(''); setNewPassword(''); setConfirm(''); setMessage('تم تغيير كلمة المرور.'); } catch (requestError: any) { setError(requestError.response?.data?.message || 'تعذر تغيير كلمة المرور.'); } finally { setSaving(false); } };
  return <AppShell><div className="admin-page-stack admin-narrow"><section className="admin-page-intro"><div><span className="admin-eyebrow">مساحة المدرس</span><h1>الإعدادات</h1><p>حدّث بيانات الحساب الإداري وكلمة المرور.</p></div></section>{(error || message) && <div className={error ? 'admin-error' : 'admin-success'}>{error || message}</div>}<section className="admin-panel admin-settings-panel"><div className="admin-settings-heading"><span><UserRound size={18} /></span><div><h2>بيانات الحساب</h2><p>الاسم الظاهر داخل لوحة التحكم.</p></div></div><label>الاسم<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>رقم الهاتف<input disabled value={user?.phone || ''} /></label><button type="button" className="admin-primary" onClick={saveProfile} disabled={saving}><Save size={15} /> حفظ البيانات</button></section><section className="admin-panel admin-settings-panel"><div className="admin-settings-heading"><span><LockKeyhole size={18} /></span><div><h2>تغيير كلمة المرور</h2><p>احتفظ بها خاصة بفريق الإدارة.</p></div></div><label>كلمة المرور الحالية<input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} /></label><label>كلمة المرور الجديدة<input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></label><label>تأكيد كلمة المرور<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label><button type="button" className="admin-secondary" onClick={savePassword} disabled={saving}><LockKeyhole size={15} /> تحديث كلمة المرور</button></section></div></AppShell>;
}
