import api from './api';

export interface Exam { _id: string; courseId: string | null | { _id: string; title: string }; educationalLevel?: string | { _id: string; nameAr: string }; title: string; timeLimitMin: number; totalMarks: number; type: 'course' | 'general'; isActive: boolean; lessonId: string | null; date: string | null; mandatoryAttendance: boolean; maxAttempts: number; reviewMode: 'closed' | 'open' | 'scheduled'; reviewReleaseAt?: string | null; shuffleQuestions: boolean; shuffleOptions: boolean; createdAt: string; updatedAt: string; }
export interface Question { _id: string; examId: string; onModel: 'Exam' | 'Assignment'; type: 'text' | 'image'; content: string; options: { id: string; text: string }[]; correct: string; explanation?: string; order: number; marks: number; }
export interface Answer { questionId: string; selectedOption: string; }
export interface Submission { _id: string; userId: { _id: string; name: string; phone: string } | string; examId: string; score: number; totalMarks: number; submittedAt: string; attemptNumber?: number; submittedReason?: 'manual' | 'auto' | 'timeout' | 'legacy'; reviewedAt?: string | null; }
export interface ExamResultGroup { student: { _id: string; name: string; phone: string; educationalLevel?: { nameAr?: string } }; attempts: Submission[]; latestAttempt: Submission; bestAttempt: Submission; }
export interface Pagination { currentPage: number; totalPages: number; totalItems: number; itemsPerPage: number; hasNextPage: boolean; hasPrevPage: boolean; }
export interface ExamListParams { type?: 'course' | 'general'; courseId?: string; educationalLevel?: string; isActive?: boolean; search?: string; page?: number; limit?: number; }

export const getAllExams = async (paramsOrPage: ExamListParams | number = {}, legacyLimit = 10) => { const params = typeof paramsOrPage === 'number' ? { page: paramsOrPage, limit: legacyLimit } : paramsOrPage; const response = await api.get<{ data: Exam[]; pagination: Pagination }>('/admin/exams', { params }); return { exams: response.data.data, pagination: response.data.pagination }; };
export const getExams = async () => (await getAllExams()).exams;
export const getExamById = async (id: string): Promise<Exam> => { const response = await api.get<{ data: { exam: Exam } }>(`/exams/${id}`); return response.data.data.exam; };
export const createExam = async (data: { title: string; type: 'course' | 'general'; courseId?: string; educationalLevel?: string; timeLimitMin: number; isActive: boolean; maxAttempts?: number; reviewMode?: 'closed' | 'open' | 'scheduled'; reviewReleaseAt?: string | null; date?: string | null; mandatoryAttendance?: boolean; shuffleQuestions?: boolean; shuffleOptions?: boolean }) => { const response = await api.post<{ data: { exam: Exam } }>('/admin/exams', data); return response.data.data.exam; };
export const updateExam = async (id: string, data: Partial<{ title: string; type: 'course' | 'general'; courseId: string | null; educationalLevel: string | null; timeLimitMin: number; isActive: boolean; maxAttempts: number; reviewMode: 'closed' | 'open' | 'scheduled'; reviewReleaseAt: string | null; date: string | null; mandatoryAttendance: boolean; shuffleQuestions: boolean; shuffleOptions: boolean }>) => { const response = await api.put<{ data: { exam: Exam } }>(`/admin/exams/${id}`, data); return response.data.data.exam; };
export const deleteExam = async (id: string) => api.delete(`/admin/exams/${id}`);
export const getExamQuestions = async (id: string): Promise<Question[]> => { const response = await api.get<{ data: { questions: Question[] } }>(`/exams/${id}/questions`); return response.data.data.questions as Question[]; };
export const createQuestion = async (data: Omit<Question, '_id' | 'onModel'> & { examId: string; onModel?: 'Exam' }) => { const response = await api.post<{ data: { question: Question } }>('/admin/questions', { ...data, onModel: 'Exam', type: 'text' }); return response.data.data.question; };
export const updateQuestion = async (id: string, data: Partial<Question>) => { const response = await api.put<{ data: { question: Question } }>(`/admin/questions/${id}`, data); return response.data.data.question; };
export const deleteQuestion = async (id: string) => api.delete(`/admin/questions/${id}`);
export const getExamSubmissions = async (id: string, page = 1, limit = 20, search = ''): Promise<{ groups: ExamResultGroup[]; pagination: Pagination }> => { const response = await api.get<{ data: ExamResultGroup[]; pagination: Pagination }>(`/admin/exams/${id}/submissions`, { params: { page, limit, search: search || undefined } }); return { groups: response.data.data, pagination: response.data.pagination }; };
